### ISSUE TITLE
[Bounty] Port Dolphin to the Universal Windows Platform

### ISSUE THREAD

**Issue by ghost** [Xbox-Homebrew/bounties#7]
We need someone with the skillset to port the "Dolphin" emulator to the Universal Windows Platform, in order for it to be usable on the Xbox line of consoles.

This port needs to have the following:
-Open-source code
-Ability to upstream from main repo
-A UI that allows users to access all of Dolphin's settings and features that are compatible with the Xbox

**Comment by abebeos** [comment]
A requirements/feasibility analysis is needed first (budget: around $300).

> -Ability to be rebased

What is this, can you elaborate, please.

**Comment by ghost** [comment]
> A requirements/feasibility analysis is needed first (budget: around $300).
> 
> > -Ability to be rebased
> 
> What is this, can you elaborate, please.

We are currently discussing how to alter the language to make sure we’re being clear. But basically, we want it to be able to be easily updatable. 

You’re interested in this bounty?

**Comment by tunip3** [comment]
> A requirements/feasibility analysis is needed first (budget: around $300).
> 
> > -Ability to be rebased
> 
> What is this, can you elaborate, please.

you want $300 to see if this can be implemented?

**Comment by abebeos** [comment]
> But basically, we want it to be able to be easily updatable.

- => Modifications should be easily applicable to the original Dolphin emulator code.
  - => Ideal: changes are merged to the original Dolphin emulator codebase

* Question: which is the relevant original Dolphin Emulator code?

> You’re interested in this bounty?

I'm interested initially to provide a requirements/feasibility analysis (the naturally required first step of such a project). Essentially we've started this above, this goes on until a document is available, which helps assessing "Is it doable, how and what is the effort?"

@tunip3 

> you want $300 to see if this can be implemented?

No only. Extract Requirements/Solution Paths, assess feasibility, see above.

The resulting document can be used to:

- Either stop the efforts
- Possibly adjust the budgets
- Reach a broader developer base which could potentially start the implementation task.

**Comment by ghost** [comment]
> > But basically, we want it to be able to be easily updatable.
> 
> * => Modifications should be easily applicable to the original Dolphin emulator code.
>   
>   * => Ideal: changes are merged to the original Dolphin emulator codebase
> 
> * Question: which is the relevant original Dolphin Emulator code?
> 
> > You’re interested in this bounty?
> 
> I'm interested initially to provide a requirements/feasibility analysis (the naturally required first step of such a project). Essentially we've started this above, this goes on until a document is available, which helps assessing "Is it doable, how and what is the effort?"
> 
> @tunip3
> 
> > you want $300 to see if this can be implemented?
> 
> No only. Extract Requirements/Solution Paths, assess feasibility, see above.
> 
> The resulting document can be used to:
> 
> * Either stop the efforts
> * Possibly adjust the budgets
> * Reach a broader developer base which could potentially start the implementation task.

Due to the way BountySource works, you get paid when the work is fulfilled. We were initially thinking of making $1000 our goal, but we can expand that to $1300 to account for the cost of the analysis.

**Comment by abebeos** [comment]
https://github.com/abebeos/dolphin-uwp/issues/1

@ReveriePass , the participants need to have much(!) higher speed and precision.

(participants: you folks communicating here, few folks for research, few folks for smaller/simpler coding tasks)


Otherwise I'll loose my interest.

## Main Rule

=> Never ignore a question

("Question: which is the relevant original Dolphin Emulator code?")

I noticed 

- an outdated https://github.com/Xbox-Homebrew/dolphin, forked from
- an even more outdated https://github.com/dolphin-emu/dolphin

Are those two repos of any relevance?

Or is the relevant repo this one: https://github.com/dolphin-emu/dolphin ?

**Comment by abebeos** [comment]
This is superstrange here.

Ok, last try: 

Apply a bounty of $100 for this:

https://github.com/abebeos/dolphin-uwp/issues/2

Once finished, you decide if you continue and apply another bounty of $200 to https://github.com/abebeos/dolphin-uwp/issues/1

Speed! You need to have it! Act fast, before I'm gone.

**Comment by ReveriePass** [comment]
Sorry, I have a fulltime job so I was waiting until 6 pm EST to respond to this, I'll see if someone else from the community can reply.

**Comment by ReveriePass** [comment]
> This is superstrange here.
> 
> Ok, last try:
> 
> Apply a bounty of $100 for this:
> 
> [abebeos/dolphin-uwp#2](https://github.com/abebeos/dolphin-uwp/issues/2)
> 
> Once finished, you decide if you continue and apply another bounty of $200 to [abebeos/dolphin-uwp#1](https://github.com/abebeos/dolphin-uwp/issues/1)
> 
> Speed! You need to have it! Act fast, before I'm gone.

Sorry, I have a fulltime job so I was waiting until 6 pm EST to respond to this, I'll see if someone else from the community can reply.

**Comment by abebeos** [comment]
k, will take another look at this tomorrow.

**Comment by ghost** [comment]
> This is superstrange here.
> 
> Ok, last try:
> 
> Apply a bounty of $100 for this:
> 
> [abebeos/dolphin-uwp#2](https://github.com/abebeos/dolphin-uwp/issues/2)
> 
> Once finished, you decide if you continue and apply another bounty of $200 to [abebeos/dolphin-uwp#1](https://github.com/abebeos/dolphin-uwp/issues/1)
> 
> Speed! You need to have it! Act fast, before I'm gone.

Hey! We appreciate your time but we are looking for someone who has some history in the emulation scene/community, so sorry about the wasted time and inconvenience. We wish you well!

**Comment by abebeos** [comment]
Oh my, you cluelessness is really fascinating.

You don't need any history for this task. I have heavy hw-design background, and 35y IT xp, and process problems naturally abstractly (e.g. do not need to know the domain).

Anyways, it looks like your attempt will become just one of the many started-but-never-finished port attempts.

Have fun.

**Comment by Gamr13** [comment]
Hi Abebeos, 

Whilst I appreciate your time here trying to lend a hand, I really don't appreciate your attitude towards them asking for some background on your analysis history. 

You should know that nobody wants to just hand out $100 - 300 to someone who not only sounds condescending but hasn't given any reason for them to believe that you are the right person for the job. 


Edit:
Abebeos' response was deleted above, here's the archived quote:
"Oh my, you cluelessness is really fascinating. 

You don't need any history for this task. I have heavy hw-design background, and 35y IT xp, and process problems naturally abstractly (e.g. do not need to know the domain).

Anyways, it looks like your attempt will become just one of the many started-but-never-finished port attempts. 

Have fun."

**Comment by abebeos** [comment]
> I really don't appreciate your attitude towards them asking for some background on your analysis history.

Get your facts together, you fracking amateurs.

Enough is enough.

**Comment by ghost** [comment]
> > I really don't appreciate your attitude towards them asking for some background on your analysis history.
> 
> Get your facts together, you fracking amateurs.
> 
> Enough is enough.

Have a great day, we wish you luck in your future endeavors!

**Comment by SternXD** [comment]
> > I really don't appreciate your attitude towards them asking for some background on your analysis history.
> 
> Get your facts together, you fracking amateurs.
> 
> Enough is enough.

We wish you the best :)

**Comment by Gamr13** [comment]
> > I really don't appreciate your attitude towards them asking for some background on your analysis history.
> 
> Get your facts together, you fracking amateurs.
> 
> Enough is enough.

That was unfortunately the wrong reply, and we will not be dealing with you further. Goodbye.

**Comment by abebeos** [comment]
Funny, now all are out and babble redundant stuff...
